image: ruby:2.1
before_script:
  - gem install jekyll
  - gem install bundler
  - bundle install --path=.bundler-cache
stages:
  - test
cache:
  paths:
    - .bundler-cache

test:
  stage: test
  script:
  - rake test